<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNntzUvp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNntzUvp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNntzUvp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNntzUvp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNntzUvp\App_KernelDevDebugContainer([
    'container.build_hash' => 'NntzUvp',
    'container.build_id' => 'f041709b',
    'container.build_time' => 1598015338,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNntzUvp');
