<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBQiSDvK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBQiSDvK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBQiSDvK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBQiSDvK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBQiSDvK\App_KernelDevDebugContainer([
    'container.build_hash' => 'BQiSDvK',
    'container.build_id' => 'efb087ea',
    'container.build_time' => 1598485831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBQiSDvK');
