<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSZemKTT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSZemKTT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSZemKTT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSZemKTT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSZemKTT\App_KernelDevDebugContainer([
    'container.build_hash' => 'SZemKTT',
    'container.build_id' => '6f7d389a',
    'container.build_time' => 1599571017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSZemKTT');
